# MSVC compiler definitions
if(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")

  set(binarySuffix vc)
  if(1200 EQUAL ${MSVC_VERSION})
    set(compilerVersion "60")
  elseif(1300 EQUAL ${MSVC_VERSION})
    set(compilerVersion "70")
  elseif(1310 EQUAL ${MSVC_VERSION})
    set(compilerVersion "71")
  elseif(1400 EQUAL ${MSVC_VERSION})
    set(compilerVersion "80")
  elseif(1500 EQUAL ${MSVC_VERSION})
    set(compilerVersion "90")
  elseif(1600 EQUAL ${MSVC_VERSION})
    set(compilerVersion "100")
  elseif(1700 EQUAL ${MSVC_VERSION})
    set(compilerVersion "110")
  elseif(1800 EQUAL ${MSVC_VERSION})
    set(compilerVersion "120")
  elseif(1900 EQUAL ${MSVC_VERSION})
    set(compilerVersion "140")
  elseif( (1910 LESS_EQUAL ${MSVC_VERSION}) AND (1920 GREATER ${MSVC_VERSION}) )
    set(compilerVersion "141")
  elseif(1920 LESS_EQUAL ${MSVC_VERSION})
    set(compilerVersion "150")
  endif()

  set(ESCOMMON_COMPILER_VERSION ${compilerVersion})
  set(ESCOMMON_BIN_SUFFIX ${binarySuffix})
  
endif()
